- name: article
  hint: true
  contents:
  - name: headline
    type: EssenceText
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    hint: true

- name: video
  hint: true
  contents:
  - name: youtube_id
    type: EssenceText
    hint: true
    validate:
    - presence

- name: taxonomy
  hint: true
  contents:
  - name: spree_taxonomy
    type: EssenceSpreeTaxonomy

- name: taxon
  hint: true
  contents:
  - name: spree_taxon
    type: EssenceSpreeTaxon

- name: product
  hint: true
  unique: true
  contents:
  - name: spree_product
    type: EssenceSpreeProduct
