# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see http://guides.alchemy-cms.com/stable/elements.html

- name: article
  hint: true
  contents:
  - name: headline
    type: EssenceText
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    hint: true

# Spree elements
- name: product
  hint: true
  unique: true
  contents:
  - name: spree_product
    type: EssenceSpreeProduct

- name: taxon
  hint: true
  contents:
  - name: spree_taxon
    type: EssenceSpreeTaxon
