# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  elements:
    - article

- name: page
  elements:
    - article
  autogenerate:
    - article

- name: taxonomy
  elements:
    - taxonomy
    - taxon
    - product
  autogenerate:
    - taxonomy

- name: taxon
  elements:
    - taxonomy
    - taxon
    - product
  autogenerate:
    - taxon

- name: product
  elements:
    - taxonomy
    - taxon
    - product
  autogenerate:
    - product
