# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  elements:
    - article

- name: page
  elements:
    - article
    - taxon
  autogenerate:
    - article

- name: products
  elements:
    - taxon
    - product
  autogenerate:
    - taxon

- name: product
  elements:
    - taxon
    - product
  autogenerate:
    - product
