# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

# Pages
- name: index
  unique: true
  elements:
    - article
  autogenerate: []

- name: page
  elements:
    - article
    - taxon
  autogenerate:
    - article

- name: products
  elements:
    - taxon
    - product
  autogenerate:
    - taxon

- name: product
  elements:
    - taxon
    - product
  autogenerate:
    - product

- name: external
  redirects_to_external: true

# Global Pages
- name: header
  unique: true
  elements: []
  autogenerate: []
  layoutpage: true

- name: footer
  unique: true
  elements: []
  autogenerate: []
  layoutpage: true
