- name: index
  elements: &elements
  - article
  - video
  - taxonomy
  - taxon
  - product

- name: page
  elements: *elements

- name: taxonomy
  elements: *elements
  autogenerate:
  - taxonomy

- name: taxon
  elements: *elements
  autogenerate:
  - taxon

- name: product
  elements: *elements
  autogenerate:
  - product
