AllCops:
  TargetRubyVersion: 2.3
AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*
Bundler/OrderedGems:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - config/initializers/devise.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
inherit_from: .rubocop_todo.yml
