version: '2'
services:
  db:
    image: postgres:9.6.2
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/web
      - node_modules:/web/node_modules
      - rubygems:/usr/local/bundle
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: .shoppu.dev
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
volumes:
  postgres:
    driver: local
  node_modules:
    driver: local
  rubygems:
    driver: local
