version: '2'
services:
  db:
    image: postgres:9.6.2
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: >
      bash -c "
      rm -f tmp/pids/server.pid
      && rails tmp:cache:clear
      & npm start -- -p 3000 -b '0.0.0.0'
      "
    volumes:
      - .:/web
      - node_modules:/web/node_modules
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: .shoppu.*
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
volumes:
  postgres:
    driver: local
  node_modules:
    driver: local
